name: note
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  msh_checkbox: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Varela
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
